name = "Trashlands"
author = "Flatts3000"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84e3132e615e99ccbcfe2d7296931b8bd222e0f6f5b9849f53552e9d0867d516"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.94"
