name = "Trashlands"
author = "Flatts3000"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ca0918581e913d64ae0214e950aa7c0f496733d75edd4b5e0b0ff428e637e05"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.100"
